<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MassTransit</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MassTransit.Interop.NServiceBus</PackageId>
    <Title>MassTransit.Interop.NServiceBus</Title>
    <PackageTags>MassTransit;NServiceBus</PackageTags>
    <Description>MassTransit Interoperability support for NServiceBus; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MassTransit.Newtonsoft\MassTransit.Newtonsoft.csproj" />
    <ProjectReference Include="..\MassTransit\MassTransit.csproj" />
  </ItemGroup>
</Project>
