<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
    <ProjectReference Include="..\..\src\MessageTransit.Newtonsoft\MessageTransit.Newtonsoft.csproj" />
    <ProjectReference Include="..\..\src\Scheduling\MessageTransit.QuartzIntegration\MessageTransit.QuartzIntegration.csproj" />
    <ProjectReference Include="..\..\src\MessageTransit.TestFramework\MessageTransit.TestFramework.csproj" />
    <ProjectReference Include="..\..\src\MessageTransit\MessageTransit.csproj" />
    <ProjectReference Include="..\MessageTransit.Tests\MessageTransit.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
