<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MassTransit</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MassTransit.Newtonsoft</PackageId>
    <Title>MassTransit.Newtonsoft</Title>
    <PackageTags>MassTransit;Newtonsoft;JSON.NET</PackageTags>
    <Description>MassTransit Newtonsoft JSON/BSON support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MassTransit\MassTransit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Newtonsoft.Json.Bson" />
  </ItemGroup>

</Project>
