<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>MessageTransit</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MessageTransit.Azure.ServiceBus.Core</PackageId>
    <Title>MessageTransit.Azure.ServiceBus.Core</Title>
    <PackageTags>MessageTransit;Azure;ServiceBus</PackageTags>
    <Description>MessageTransit Azure Service Bus Core transport support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <ProjectReference Include="..\..\MessageTransit\MessageTransit.csproj" />
  </ItemGroup>

</Project>
