<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>MessageTransit</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MessageTransit.RabbitMQ</PackageId>
    <Title>MessageTransit.RabbitMQ</Title>
    <PackageTags>MessageTransit;RabbitMQ</PackageTags>
    <Description>MessageTransit RabbitMQ transport support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MessageTransit\MessageTransit.csproj" />
  </ItemGroup>
</Project>
