<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../signing.props"/>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MassTransit</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MassTransit.MessagePack</PackageId>
    <Title>MassTransit.MessagePack</Title>
    <PackageTags>MassTransit;MessagePack;MsgPack</PackageTags>
    <Description>MassTransit MessagePack support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MassTransit.Abstractions\MassTransit.Abstractions.csproj"/>
    <ProjectReference Include="..\MassTransit\MassTransit.csproj"/>
  </ItemGroup>

</Project>
