<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MessageTransit</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MessageTransit.SqlTransport.PostgreSQL</PackageId>
    <Title>MessageTransit.SqlTransport.PostgreSQL</Title>
    <PackageTags>MessageTransit;Database;Transport;PostgreSQL;npgsql</PackageTags>
    <Description>MessageTransit PostgreSQL Database Transport; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MessageTransit\MessageTransit.csproj" />
  </ItemGroup>

</Project>
