<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>MessageTransit</RootNamespace>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MessageTransit.WebJobs.ServiceBus</PackageId>
    <Title>MessageTransit.WebJobs.ServiceBus</Title>
    <PackageTags>MessageTransit;Azure;WebJobs;AzureFunctions</PackageTags>
    <Description>MessageTransit Azure WebJobs Service Bus support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" />
    <ProjectReference Include="..\MessageTransit.Azure.ServiceBus.Core\MessageTransit.Azure.ServiceBus.Core.csproj" />
    <ProjectReference Include="..\..\MessageTransit\MessageTransit.csproj" />
  </ItemGroup>
</Project>
