<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../signing.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>MessageTransit</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MessageTransit.AmazonSQS</PackageId>
    <Title>MessageTransit.AmazonSQS</Title>
    <PackageTags>MessageTransit;AmazonSQS</PackageTags>
    <Description>MessageTransit Amazon SQS transport support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleNotificationService" />
    <PackageReference Include="AWSSDK.SQS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MessageTransit\MessageTransit.csproj" />
  </ItemGroup>
</Project>
