<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
    <ProjectReference Include="..\..\src\MessageTransit.Newtonsoft\MessageTransit.Newtonsoft.csproj" />
    <ProjectReference Include="..\..\src\Transports\MessageTransit.Azure.ServiceBus.Core\MessageTransit.Azure.ServiceBus.Core.csproj" />
    <ProjectReference Include="..\..\src\Scheduling\MessageTransit.QuartzIntegration\MessageTransit.QuartzIntegration.csproj" />
    <ProjectReference Include="..\..\src\MessageTransit.TestFramework\MessageTransit.TestFramework.csproj" />
    <ProjectReference Include="..\..\src\MessageTransit\MessageTransit.csproj" />
    <ProjectReference Include="..\..\src\Persistence\MessageTransit.Azure.Storage\MessageTransit.Azure.Storage.csproj" />
  </ItemGroup>

</Project>
