<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MassTransit</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MassTransit.SqlTransport.SqlServer</PackageId>
    <Title>MassTransit.SqlTransport.SQL Server</Title>
    <PackageTags>MassTransit;Database;Transport;SQL Server;Microsoft;Azure;SQL</PackageTags>
    <Description>MassTransit SQL Server Transport; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MassTransit\MassTransit.csproj" />
  </ItemGroup>
</Project>
